# Generated by Django 2.2.4 on 2020-09-29 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='group_id')),
                ('group_name', models.CharField(max_length=20, verbose_name='group_name')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Group', verbose_name='group_id')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='chat_id')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Group', verbose_name='group_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('user_id', 'group_id'), name='belongs'),
        ),
    ]
