# Generated by Django 2.2.4 on 2020-09-20 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='group_id')),
                ('group_name', models.CharField(max_length=20, verbose_name='group_name')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='mail')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='chat_id')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Group', verbose_name='group_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.User', verbose_name='user_id')),
            ],
            options={
                'db_table': 'chat_history',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.User', verbose_name='user_id')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Group', verbose_name='group_id')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.AddConstraint(
            model_name='groupmember',
            constraint=models.UniqueConstraint(fields=('user_id', 'group_id'), name='belongs'),
        ),
    ]
